### ISSUE TITLE
Invalid authenticity tokens generating 500 internal server error responses

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/hpi-explorer#104]
From the log files:

I, [2015-02-11T03:12:28.234400 #25030]  INFO -- : Started POST "/app/hpi/preview" for 106.120.110.181 at 2015-02-11 03:12:28 +0000
I, [2015-02-11T03:12:28.235152 #25030]  INFO -- : Processing by PreviewController#create as GIF
I, [2015-02-11T03:12:28.235222 #25030]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"LwTEAP1LL2lyixP8OyDp/9sCUHMwVVyh9Yqb6W/6L9Y=", "from_m"=>"0", "from_y"=>"2014", "to_m"=>"1", "to_y"=>"2015", "m_hpi"=>"1", "m_chm"=>"1", "m_chy"=>"1", "m_vol"=>"1", "m_ap"=>"1", "m_apd"=>"d", "m_apsd"=>"d", "source"=>"preview_form", "loc_0"=>"Manchester", "loc_uri_0"=>"http://landregistry.data.gov.uk/id/region/manchester"}
W, [2015-02-11T03:12:28.235609 #25030]  WARN -- : Can't verify CSRF token authenticity
W, [2015-02-11T03:12:28.235685 #25030]  WARN -- : No explicit error page for exception ActionController::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken
I, [2015-02-11T03:12:28.236292 #25030]  INFO -- :   Rendered public/landing/500.html (0.1ms)
I, [2015-02-11T03:12:28.236388 #25030]  INFO -- : Completed 500 Internal Server Error in 1ms (Views: 0.3ms)

**Comment by ijdickinson** [comment]
Nothing I can do to prevent these happening (stale cached pages, presumably in the browser since afaik you clear the httpd cache during a deploy). However, I've changed the controller to log a 403 forbidden instead of a 500
