### ISSUE TITLE
404 errors on images/sort_both.png

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/hpi-explorer#106]
Seeing a few of these:

There are files 

./public/assets/dataTables/sort_both-3f7e8847b62871fbfdf9171df8a793f2.png
./public/assets/dataTables/foundation/sort_both-3f7e8847b62871fbfdf9171df8a793f2.png

From the production.log file

[[
I, [2015-02-11T15:24:12.806092 #29700]  INFO -- : Started GET "/app/hpi/images/sort_both.png" for 90.152.126.246 at 2015-02-11 15:24:12 +0000
I, [2015-02-11T15:24:12.807011 #29700]  INFO -- : Processing by ApplicationController#render_404 as PNG
I, [2015-02-11T15:24:12.807062 #29700]  INFO -- :   Parameters: {"unmatched_route"=>"images/sort_both"}
I, [2015-02-11T15:24:12.807918 #29700]  INFO -- :   Rendered text template (0.0ms)
I, [2015-02-11T15:24:12.808079 #29700]  INFO -- : Completed 404 Not Found in 1ms (Views: 0.3ms)

]]

**Comment by ijdickinson** [comment]
Looks like a dup of rweng/jquery-datatables-rails#153 . Updating the `Gemfile` should fix

**Comment by ijdickinson** [comment]
Commit pushed but not deployed yet
