### ISSUE TITLE
Post to /app/hpi/preview causing 500 error

### ISSUE THREAD

**Issue by ijdickinson** [epimorphics/hpi-explorer#107]
Reported by @afs. Possibly related to #105, but the symptoms are different.

Sample log entry:

    I, [2015-05-27T09:42:24.149397 #27483]  INFO -- : Started POST "/app/hpi/preview" for 86.28.18.1 at 2015-05-27 09:42:24 +0000
    I, [2015-05-27T09:42:24.150373 #27483]  INFO -- : Processing by PreviewController#create as JSON
    I, [2015-05-27T09:42:24.150439 #27483]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"PGyTObzXYptOgVrQ8WwAiRgdSuNquHJ44MSDrNZSO9Q=", "from_m"=>"0", "fr
    om_y"=>"2014", "to_m"=>"4", "to_y"=>"2015", "m_hpi"=>"1", "source"=>"preview_form", "loc_0"=>"Kensington and Chelsea", "loc_uri_0"=>"http://landregistry.data.gov.uk/i
    d/region/kensington-and-chelsea"}
    I, [2015-05-27T09:42:24.178290 #27483]  INFO -- :   Rendered hpi/_selected_location.html.haml (9.5ms)
    I, [2015-05-27T09:42:24.187700 #27483]  INFO -- :   Rendered hpi/_selected_location.html.haml (9.0ms)
    I, [2015-05-27T09:42:24.188752 #27483]  INFO -- :   Rendered preview/_preview.html.haml (10.2ms)
    I, [2015-05-27T09:42:24.189338 #27483]  INFO -- : Completed 200 OK in 39ms (Views: 0.5ms)
    I, [2015-05-27T09:42:26.806104 #27483]  INFO -- : Started GET "/app/hpi/view?from_m=4&from_y=2014&to_m=4&to_y=2015" for 66.249.64.250 at 2015-05-27 09:42:26 +0000
    I, [2015-05-27T09:42:26.806987 #27483]  INFO -- : Processing by ViewController#index as HTML
    I, [2015-05-27T09:42:26.807040 #27483]  INFO -- :   Parameters: {"from_m"=>"4", "from_y"=>"2014", "to_m"=>"4", "to_y"=>"2015"}
    W, [2015-05-27T09:42:26.811192 #27483]  WARN -- : No explicit error page for exception Failed to post to http://localhost:8080/dsapi/dataset/hpi/data: 400 - RuntimeEr
    ror
    I, [2015-05-27T09:42:26.811923 #27483]  INFO -- :   Rendered public/landing/500.html (0.1ms)
    I, [2015-05-27T09:42:26.812053 #27483]  INFO -- : Completed 500 Internal Server Error in 5ms (Views: 0.5ms)

**Comment by afs** [comment]
Fishing out some Apache log entries with examples of 200 and 500 responses:

`92.19.139.6 - - [26/May/2015:11:30:07 +0000] "POST /app/hpi/preview HTTP/1.1" 500 4963  "http://landregistry.data.gov.uk/app/hpi" "Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; ASU2JS; rv:11.0) like Gecko"`

`131.211.72.188 - - [26/May/2015:11:42:31 +0000] "POST /app/hpi/preview HTTP/1.1" 500 4963  "http://landregistry.data.gov.uk/app/hpi/search?compare=1&loc_0=Greater+London&loc_uri_0=http%3A%2F%2Flandregistry.data.gov.uk%2Fid%2Fregion%2Fgreater-london&search_1=New+York+city+&source=search_form" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36"`

but some work:

`62.254.90.80 - - [27/May/2015:00:11:34 +0000] "POST /app/hpi/preview HTTP/1.1" 200 5094  "http://landregistry.data.gov.uk/app/hpi/" "Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0"`

**Comment by bwm-epimorphics** [comment]
This may be similar except this time the method name is 'pry'.

I, [2015-05-26T11:42:38.735675 #29466]  INFO -- : Started POST "/app/hpi/preview" for 131.211.72.188 at 2015-05-26 11:42:38 +0000
I, [2015-05-26T11:42:38.736251 #29466]  INFO -- : Processing by PreviewController#create as JSON
I, [2015-05-26T11:42:38.736582 #29466]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"AlD2Lu5O241JLFd4n9PJaJz+qzMVPppksz8tYTgVtPk=", "from_m"=>"0", "from_y"=>"1995", "to_m"=>"0", "to_y"=>"2015", "m_hpi"=>"1", "m_chy"=>"1", "m_ap"=>"1", "loc_0"=>"Greater London", "loc_uri_0"=>"http://landregistry.data.gov.uk/id/region/greater-london", "search_1"=>"New York city ", "source"=>"preview_form"}
W, [2015-05-26T11:42:38.737116 #29466]  WARN -- : No explicit error page for exception undefined method `pry' for #<Binding:0x0000000553fd40> - NoMethodError
I, [2015-05-26T11:42:38.737579 #29466]  INFO -- :   Rendered public/landing/500.html (0.0ms)
I, [2015-05-26T11:42:38.737676 #29466]  INFO -- : Completed 500 Internal Server Error in 1ms (Views: 0.3ms)

**Comment by ijdickinson** [comment]
I can't see any instances of this happening in the log files now. Happy to re-open (or open a new specific issue) if there are more symptoms
