### ISSUE TITLE
500 Error on failure to verify CSRF token

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/hpi-explorer#108]
From the logfile

I, [2015-05-26T11:28:01.865776 #29466]  INFO -- : Processing by PreviewController#create as JSON
I, [2015-05-26T11:28:01.865847 #29466]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"A
lBfRI/D98u3z+BIa72UCtmFx6Dljd2YP23voz148mc=", "from_m"=>"4", "from_y"=>"2014", "to_m"=>"4", "to_y"=>"2
015", "m_hpi"=>"1", "m_ap"=>"1", "source"=>"preview_form", "loc_0"=>"Northumberland", "loc_uri_0"=>"ht
tp://landregistry.data.gov.uk/id/region/northumberland"}
W, [2015-05-26T11:28:01.866145 #29466]  WARN -- : Can't verify CSRF token authenticity
W, [2015-05-26T11:28:01.866260 #29466]  WARN -- : No explicit error page for exception ActionControlle
r::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken
I, [2015-05-26T11:28:01.866937 #29466]  INFO -- :   Rendered public/landing/500.html (0.1ms)
I, [2015-05-26T11:28:01.867063 #29466]  INFO -- : Completed 500 Internal Server Error in 1ms (Views: 0.5ms)

May be related to #107

**Comment by ijdickinson** [comment]
This is a different issue to #107. CSRF failures are not solvable by my code: it's either people with stale forms, or scripts synthesising form URLs outwith the form. However, a CSRF failure should be logged as 403 forbidden, not 500, which would then not contribute to the internal error threshold check.

**Comment by ijdickinson** [comment]
Such errors should be generating a 403 error now.

**Comment by bwm-epimorphics** [comment]
This is still happening.  From a recent log file:

[[
I, [2015-12-09T05:30:47.704555 #30243]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"VcOpezWWM2d0yElkToL2SsDKlG4h5/6X7eCbX0ItkJPdQWebOmGm92mN7BHXEkEbZ3dOqJDl41iU7bOFLfXy8Q==", "from_m"=>"11",
 "from_y"=>"1995", "to_m"=>"11", "to_y"=>"2015", "m_hpi"=>"1", "source"=>"preview_form", "loc_0"=>"North West", "loc_uri_0"=>"http://landregistry.data.gov.uk/id/region/north-west"}
W, [2015-12-09T05:30:47.705117 #30243]  WARN -- : Can't verify CSRF token authenticity
W, [2015-12-09T05:30:47.705247 #30243]  WARN -- : Invalid authenticity token ActionController::InvalidAuthenticityToken
I, [2015-12-09T05:30:47.708048 #30243]  INFO -- : Completed 500 Internal Server Error in 3ms
F, [2015-12-09T05:30:47.708840 #30243] FATAL -- : 
ActionView::MissingTemplate (Missing template var/www/landregistry/hpi/releases/9c7ed68c059952ebf557091e2785cbbaa4e1118d/public/landing/403 with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :jbuilder, :haml]}. Searched in:
  * "/var/www/landregistry/hpi/releases/9c7ed68c059952ebf557091e2785cbbaa4e1118d/app/views"
  * "/var/www/landregistry/hpi/releases/9c7ed68c059952ebf557091e2785cbbaa4e1118d/vendor/bundle/ruby/2.1.0/bundler/gems/qonsole-rails-d3fae8dcdeef/app/views"
  * "/var/www/landregistry/hpi/releases/9c7ed68c059952ebf557091e2785cbbaa4e1118d"
  * "/"
):
  app/controllers/application_controller.rb:47:in `block (2 levels) in render_error'
  app/controllers/application_controller.rb:46:in `render_error'
  app/controllers/application_controller.rb:34:in `render_exception'
  app/middleware/catch_request_errors.rb:8:in `call'
]]

**Comment by ijdickinson** [comment]
> This is still happening

No, it isn't. This is a different problem. I've created #113, closing this one again.
