### ISSUE TITLE
Towns with an ' in them not returning any search results 

### ISSUE THREAD

**Issue by MalcolmShazell** [epimorphics/hpi-explorer#109]
I have tried with Bishop's Stortford and king's lynn got the same problem - I’m sure it is the ' causing the problem - most probably its invalidating the sparql query I tried running the following SPARQL with a town of DEAL which returned results and bishop's stortford which didn't what is confusing me is both bits of SPARQL appear to parse correctly.

prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix sr: <http://data.ordnancesurvey.co.uk/ontology/spatialrelations/>
prefix lrhpi: <http://landregistry.data.gov.uk/def/hpi/>
prefix lrppi: <http://landregistry.data.gov.uk/def/ppi/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix lrcommon: <http://landregistry.data.gov.uk/def/common/>

# Returns the Price Paid data from the default graph for each transaction record having
# an address with the given postcode.
# The postcode to query is set in the line - ?address_instance common:postcode "PL6 8RU"^^xsd:string .

SELECT ?paon ?saon ?street ?town ?county ?postcode ?amount ?date
WHERE
{
  ?transx lrppi:pricePaid ?amount ;
          lrppi:transactionDate ?date ;
          lrppi:propertyAddress ?addr.
  
  ?addr lrcommon:town "Bishop's Stortford"^^xsd:string.
  ?addr lrcommon:town ?town.
  
  OPTIONAL {?addr lrcommon:county ?county}
  OPTIONAL {?addr lrcommon:paon ?paon}
  OPTIONAL {?addr lrcommon:saon ?saon}
  OPTIONAL {?addr lrcommon:street ?street}
  OPTIONAL {?addr lrcommon:postcode ?postcode}

}
ORDER BY ?amount

**Comment by ijdickinson** [comment]
Since this is a PPD issue, I've moved the bugreport to the PPD repo.
