### ISSUE TITLE
On dev/staging servers qonsole form, the sparql endpoint should point to the appropriate dev/staging endpoint

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/hpi-explorer#110]
~~The sparql endpoint in the qonsole sparql form is hard coded to http://landregistry.data.gov.uk/...~~

The configuration file used to specify SPARQL endpoints currently requires a fully qualified domain name for the SPARQL server.

This means that either we use the Chef config to provide individual `qonsole.json` files for each environment, or the dev and staging machines query the production servers, not their respective data servers.

One way to enable those servers to send the query the correct endpoint would be to make the query endpoint domain accept relative URLs,  e.g. `/landregistry/query.`

**Comment by ijdickinson** [comment]
Fix deployed.
