### ISSUE TITLE
lr-pres-dev: show full results and download data buttons not working

### ISSUE THREAD

**Issue by bwm-epimorphics** [epimorphics/hpi-explorer#111]
1) Go to the HPI app http://lr-pres-dev.epimorphics.net/app/hpi
2) type plymouth and select City of Plymouth as the area
3) press green "show full results" button

Get 404 response page.

The app log includes:  "unmatched_route"=>"app/hpi/view"

Similarly for the "download data" button in which case the app log includes:  "unmatched_route"=>"app/hpi/hpi_data"

**Comment by ijdickinson** [comment]
This was a second instance of the regression that first showed up on PPD. It's actually a workaround that's no longer needed since a platform bug in Rails got fixed.

Fix deployed to `-dev`

**Comment by bwm-epimorphics** [comment]
Confirmed fixed.
